export default {
  registerSuccess: false,
  registerFail: false,
  loginSuccess: false,
  nonExistingUser: false,
  wrongPassword: false,
  firstname: '',
  email: '',
  logged: false,
  loaded: false,
  createdSpace: '',
  spaces: [],
  joinedSpace: false,
  joiningWhileUnlogged: false,
  tryToJoin: false,
  space: false,
  messagesReceived: false,
  messagesSent: false,
  spaceMembers: []
}
