export default {
  registerSuccess: false,
  registerFail: false,
  loginSuccess: false,
  nonExistingUser: false,
  wrongPassword: false,
  firstname: '',
  email: '',
  logged: false,
  loaded: false,
  createdSpace: '',
  spaces: [],
  spaceToJoin: '',
  joinedSpace: false,
  joiningWhileUnlogged: false,
  tryToJoin: false,
  sessionUserSpaces: [],
  space: false,
  spaceMembers: [],
  sendMessageSuccess: false,
  messagesReceived: false,
  messagesSent: false
}
